export default {
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  GET_ACCOUNTS_FULFILLED: 'GET_ACCOUNTS_FULFILLED',
  GET_ACCOUNTS_PENDING: 'GET_ACCOUNTS_PENDING',
  GET_ACCOUNTS_REJECTED: 'GET_ACCOUNTS_REJECTED',

  GET_ACCOUNT: 'GET_ACCOUNT',
  GET_ACCOUNT_FULFILLED: 'GET_ACCOUNT_FULFILLED',
  GET_ACCOUNT_PENDING: 'GET_ACCOUNT_PENDING',
  GET_ACCOUNT_REJECTED: 'GET_ACCOUNT_REJECTED',

  GET_TYPE: 'GET_TYPE',
  GET_TYPE_FULFILLED: 'GET_TYPE_FULFILLED',
  GET_TYPE_PENDING: 'GET_TYPE_PENDING',
  GET_TYPE_REJECTED: 'GET_TYPE_REJECTED',

  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_ACCOUNT_FULFILLED: 'CREATE_ACCOUNT_FULFILLED',
  CREATE_ACCOUNT_PENDING: 'CREATE_ACCOUNT_PENDING',
  CREATE_ACCOUNT_REJECTED: 'CREATE_ACCOUNT_REJECTED',

  RESET_ACCOUNT: 'RESET_ACCOUNT',

  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  DELETE_ACCOUNT_FULFILLED: 'DELETE_ACCOUNT_FULFILLED',
  DELETE_ACCOUNT_PENDING: 'DELETE_ACCOUNT_PENDING',
  DELETE_ACCOUNT_REJECTED: 'DELETE_ACCOUNT_REJECTED',

  UPDATE_STATUS: 'UPDATE_STATUS',
  UPDATE_STATUS_FULFILLED: 'UPDATE_STATUS_FULFILLED',
  UPDATE_STATUS_PENDING: 'UPDATE_STATUS_PENDING',
  UPDATE_STATUS_REJECTED: 'UPDATE_STATUS_REJECTED',

  UPDATE_ROLE: 'UPDATE_ROLE',
  UPDATE_ROLE_FULFILLED: 'UPDATE_ROLE_FULFILLED',
  UPDATE_ROLE_PENDING: 'UPDATE_ROLE_PENDING',
  UPDATE_ROLE_REJECTED: 'UPDATE_ROLE_REJECTED',
};
