/**
 * Booking related action types.
 */
export default {
  GET_NOT_COLLECTED_BOOKINGS: 'GET_NOT_COLLECTED_BOOKINGS',
  GET_NOT_COLLECTED_BOOKINGS_FULFILLED: 'GET_NOT_COLLECTED_BOOKINGS_FULFILLED',
  GET_NOT_COLLECTED_BOOKINGS_PENDING: 'GET_NOT_COLLECTED_BOOKINGS_PENDING',
  GET_NOT_COLLECTED_BOOKINGS_REJECTED: 'GET_NOT_COLLECTED_BOOKINGS_REJECTED',

  GET_BOOKINGS: 'GET_BOOKINGS',
  GET_BOOKINGS_FULFILLED: 'GET_BOOKINGS_FULFILLED',
  GET_BOOKINGS_PENDING: 'GET_BOOKINGS_PENDING',
  GET_BOOKINGS_REJECTED: 'GET_BOOKINGS_REJECTED',

  GET_BOOKING: 'GET_BOOKING',
  GET_BOOKING_FULFILLED: 'GET_BOOKING_FULFILLED',
  GET_BOOKING_PENDING: 'GET_BOOKING_PENDING',
  GET_BOOKING_REJECTED: 'GET_BOOKING_REJECTED',

  CREATE_BOOKING: 'CREATE_BOOKING',
  CREATE_BOOKING_FULFILLED: 'CREATE_BOOKING_FULFILLED',
  CREATE_BOOKING_PENDING: 'CREATE_BOOKING_PENDING',
  CREATE_BOOKING_REJECTED: 'CREATE_BOOKING_REJECTED',

  DELETE_BOOKINGS: 'DELETE_BOOKINGS',
  DELETE_BOOKINGS_FULFILLED: 'DELETE_BOOKINGS_FULFILLED',
  DELETE_BOOKINGS_PENDING: 'DELETE_BOOKINGS_PENDING',
  DELETE_BOOKINGS_REJECTED: 'DELETE_BOOKINGS_REJECTED',

  UPDATE_BOOKING: 'UPDATE_BOOKING',
  UPDATE_BOOKING_FULFILLED: 'UPDATE_BOOKING_FULFILLED',
  UPDATE_BOOKING_PENDING: 'UPDATE_BOOKING_PENDING',
  UPDATE_BOOKING_REJECTED: 'UPDATE_BOOKING_REJECTED',
};
