export default {
  GET_COLLECTIONS: 'GET_COLLECTIONS',
  GET_COLLECTIONS_FULFILLED: 'GET_COLLECTIONS_FULFILLED',
  GET_COLLECTIONS_PENDING: 'GET_COLLECTIONS_PENDING',
  GET_COLLECTIONS_REJECTED: 'GET_COLLECTIONS_REJECTED',

  GET_COLLECTION: 'GET_COLLECTION',
  GET_COLLECTION_FULFILLED: 'GET_COLLECTION_FULFILLED',
  GET_COLLECTION_PENDING: 'GET_COLLECTION_PENDING',
  GET_COLLECTION_REJECTED: 'GET_COLLECTION_REJECTED',
  RESET_COLLECTION: 'RESET_COLLECTION',

  CREATE_COLLECTION: 'CREATE_COLLECTION',
  CREATE_COLLECTION_FULFILLED: 'CREATE_COLLECTION_FULFILLED',
  CREATE_COLLECTION_PENDING: 'CREATE_COLLECTION_PENDING',
  CREATE_COLLECTION_REJECTED: 'CREATE_COLLECTION_REJECTED',
};
