export default {
  GET_COLLECTIONS: 'GET_COLLECTIONS',
  GET_COLLECTIONS_FULFILLED: 'GET_COLLECTIONS_FULFILLED',
  GET_COLLECTIONS_PENDING: 'GET_COLLECTIONS_PENDING',
  GET_COLLECTIONS_REJECTED: 'GET_COLLECTIONS_REJECTED',

  GET_COLLECTION: 'GET_COLLECTION',
  GET_COLLECTION_FULFILLED: 'GET_COLLECTION_FULFILLED',
  GET_COLLECTION_PENDING: 'GET_COLLECTION_PENDING',
  GET_COLLECTION_REJECTED: 'GET_COLLECTION_REJECTED',

  PROCESS_COLLECTION: 'PROCESS_COLLECTION',
  PROCESS_COLLECTION_FULFILLED: 'PROCESS_COLLECTION_FULFILLED',
  PROCESS_COLLECTION_PENDING: 'PROCESS_COLLECTION_PENDING',
  PROCESS_COLLECTION_REJECTED: 'PROCESS_COLLECTION_REJECTED',
};
