/**
 * Users related action types.
 */
export default {
  GET_CUSTOMERS: 'GET_CUSTOMERS',
  GET_CUSTOMERS_FULFILLED: 'GET_CUSTOMERS_FULFILLED',
  GET_CUSTOMERS_PENDING: 'GET_CUSTOMERS_PENDING',
  GET_CUSTOMERS_REJECTED: 'GET_CUSTOMERS_REJECTED',
};
