const COLLECTION = {
  COLLECTION_DATA: {
    dataId: 1,
    bookingId: 2,
    matchToSchedule: true,
    date: '01/09/2020',
    customerId: 3,
    customerName: 'Test Customer 3',
    customerEmail: 'customer@test.com',
    driverId: 1,
    driverName: 'Test driver 1',
    driverEmail: 'driver@test.com',
    processorId: 4,
    processorName: 'Test Processor 4',
    processorEmail: 'processor@demo.com',
    processedDate: '25/09/2020',
    siteId: 'B001',
    siteName: 'Test site 1',
    location: '171 Brisbane Rd',
    notes: 'test creation',
    items: [
      { materialCategory: 'Media', weight: 100.0, comments: 'no comments' },
      { materialCategory: 'Media', weight: 200.0, comments: 'no comments' },
    ],
    status: 'PROCESSED',
    containers: [
      { containerID: 1, containerType: 'Cage', ccId: 713, quantity: 1 },
    ],
  },
  COLLECTIONS_DATA: [
    {
      bookingDate: '30/07/2019',
      collectionDate: '01/08/2019',
      customerId: 1,
      customerName: 'Customer 1',
      dataId: 1,
      note: '',
      sid: 1,
      siteId: 'B001',
      siteName: 'Test site 1',
      status: ['COLLECTED'],
    },
    {
      bookingDate: '30/07/2019',
      collectionDate: '01/08/2019',
      customerId: 2,
      customerName: 'Customer 2',
      dataId: 2,
      note: '',
      sid: 2,
      siteId: 'B002',
      siteName: 'Test site 2',
      status: ['COLLECTED'],
    },
  ],
  NEW_COLLECTION_DATA: {
    booking: 1,
    date: '07/10/2020',
    scheduleMatched: true,
    notes: 'Test create collection',
    items: [
      {
        containerID: 1,
        containerType: 'Cage',
        wasteType: 'IT & Electrical',
        weight: '2',
      },
    ],
  },
};

const BOOKING = {
  BOOKING_DATA: {
    dataId: 4,
    customerId: 2,
    customerName: 'Melbourne Law School',
    sid: 1,
    siteId: 'A002',
    siteName: 'demo',
    location: 'demo',
    bookingDate: '2020-08-23',
    collectionDate: '2021-01-22',
    status: ['BOOKED'],
  },
  BOOKINGS_DATA: [
    {
      dataId: 1,
      customerId: 1,
      customerName: 'Melbourne School of Engineering',
      sid: 3,
      siteId: 'A001',
      siteName: 'demo',
      bookingDate: '2020-08-23',
      collectionDate: '2021-08-20',
      status: ['BOOKED'],
    },
    {
      dataId: 2,
      customerId: 2,
      customerName: 'Melbourne Law School',
      sid: 1,
      siteId: 'A002',
      siteName: 'demo',
      bookingDate: '2020-08-23',
      collectionDate: '2021-01-22',
      status: ['BOOKED', 'PENDING'],
    },
  ],
  NEW_BOOKING_DATA: {
    customerId: 1,
    sid: 3,
    bookingDate: '2020-08-23',
    collectionDate: '2021-01-22',
    note: 'note',
  },
  UPDATE_BOOKING_DATA: {
    dataId: 1,
    customerId: 1,
    sid: 3,
    bookingDate: '2020-08-23',
    collectionDate: '2021-01-22',
    note: 'note',
  },
};

export { BOOKING, COLLECTION };
